(function(){
const API="https://rwnesehhsblejmrbzzsu.supabase.co/functions/v1/reel-api";
const KEY="sb_publishable_3vG6klw0_89fiTeXRcFPdg_EmtjhDWi";
const api=(action,body={})=>fetch(API,{method:"POST",headers:{"Content-Type":"application/json",apikey:KEY,Authorization:"Bearer "+KEY},body:JSON.stringify({action,...body})});
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const fmt=ts=>new Date(ts).toLocaleString([], {day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"});
const cairo=ts=>{const p=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Cairo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",hourCycle:"h23"}).formatToParts(new Date(ts));const g=n=>Number(p.find(x=>x.type===n)?.value||0);return{y:g("year"),m:g("month"),d:g("day"),h:g("hour")};};
const dayKey=ts=>{const p=cairo(ts);return p.y+"-"+String(p.m).padStart(2,"0")+"-"+String(p.d).padStart(2,"0")};
window.showMonitoring=async function(id){
 const r=(window.reelsData||[]).find(x=>String(x.id)===String(id));
 if(!r)return;
 const overlay=document.createElement("div");overlay.className="monitor-modal";
 overlay.innerHTML="<div class='monitor-sheet'><button class='close' id='monitorClose'>×</button><div class='monitor-head'><div><h2>Monitoring</h2><div class='monitor-sub'>"+esc(r.title||"Untitled Reel")+"</div></div><button class='monitor-edit-icon' id='monitorEdit' title='Edit monitoring' aria-label='Edit monitoring'>✎</button></div><div class='monitor-tabs'><button class='monitor-tab active' data-tab='growth'>View Growth</button><button class='monitor-tab' data-tab='drops'>Drops</button></div><div id='monitorBody' class='monitor-body'><div class='loading'>Loading monitoring...</div></div></div>";
 document.body.appendChild(overlay);
 const close=()=>overlay.remove();overlay.querySelector("#monitorClose").onclick=close;overlay.querySelector("#monitorEdit").onclick=async()=>{close();if(window.editMonitoring)await window.editMonitoring(id)};
 let history=[];
 const renderGrowth=()=>{
  const targets=r.hourly_targets&&typeof r.hourly_targets==="object"?r.hourly_targets:{};
  const today=dayKey(new Date().toISOString()),days=[...new Set([today,...history.map(x=>dayKey(x.captured_at))])].sort().reverse();
  const now=cairo(new Date().toISOString()),body=overlay.querySelector("#monitorBody");
  body.innerHTML="<div class='monitor-summary'><span>Fixed clock hours · Cairo time</span><b>Each date is a separate 24-hour chain</b></div>"+days.map((dk,di)=>{
   const [y,m,d]=dk.split("-"),rows=Array.from({length:24},(_,h)=>{const arr=history.filter(x=>dayKey(x.captured_at)===dk&&cairo(x.captured_at).h===h).sort((a,b)=>new Date(a.captured_at)-new Date(b.captured_at));const t=targets[String(h)]||targets[String(h).padStart(2,"0")]||{};return{h,minV:Number(t.views||0),minL:Number(t.likes||0),arr}});
   const hours=rows.map(w=>{const arr=w.arr,has=w.minV>0||w.minL>0,complete=dk!==today||w.h<now.h;let status=has?"nodata":"no-target",result="—";if(has&&arr.length>=1&&complete){const a=arr[0],b=arr[arr.length-1],dv=Number(b.views||0)-Number(a.views||0),dl=Number(b.likes||0)-Number(a.likes||0),pass=(w.minV<=0||dv>=w.minV)&&(w.minL<=0||dl>=w.minL);status=pass?"pass":"fail";result=(dv>=0?"+":"")+dv.toLocaleString()+" views · "+(dl>=0?"+":"")+dl.toLocaleString()+" likes"}else if(has&&dk===today&&w.h===now.h)status="pending";const label=status==="pass"?"PASS":status==="fail"?"NOT MET":status==="pending"?"IN PROGRESS":status==="nodata"?"NO DATA":"—";const snaps=arr.length?arr.slice().reverse().map((s,i,a)=>{const p=a[i+1],dv=p?Number(s.views||0)-Number(p.views||0):0,dl=p?Number(s.likes||0)-Number(p.likes||0):0;return "<div class='monitor-snap'><span>"+esc(fmt(s.captured_at))+"</span><b>"+Number(s.views||0).toLocaleString()+" views</b><em class='"+(dv>0?"up":dv<0?"down":"neutral")+"'>"+(dv>=0?"+":"")+dv.toLocaleString()+" views</em><b>"+Number(s.likes||0).toLocaleString()+" likes</b><em class='"+(dl>0?"up":dl<0?"down":"neutral")+"'>"+(dl>=0?"+":"")+dl.toLocaleString()+" likes</em></div>"}).join(""):"<div class='monitor-snaps-empty'>No data yet for this hour.</div>";return "<div class='monitor-row'><div class='monitor-row-top'><div class='monitor-number'>"+String(w.h).padStart(2,"0")+"</div><div class='monitor-period'><b>"+String(w.h).padStart(2,"0")+":00 – "+String(w.h).padStart(2,"0")+":59</b><small>Min views: "+(w.minV||0).toLocaleString()+" · Min likes: "+(w.minL||0).toLocaleString()+" · "+arr.length+" snapshots</small></div><div class='monitor-status "+status+"'>"+label+"</div></div><button type='button' class='monitor-expand' aria-expanded='false'>↓</button><div class='monitor-result collapsed'><div class='monitor-snaps'>"+(arr.length&&has?"<div class='monitor-growth'><span>Actual growth</span><strong>"+esc(result)+"</strong></div>":"")+snaps+"</div></div></div>"}).join("");
   return "<div class='monitor-day'><button type='button' class='monitor-day-toggle' aria-expanded='"+(di===0?"true":"false")+"'><span>"+d+"/"+m+"/"+y+"</span><b>"+rows.reduce((n,x)=>n+x.arr.length,0)+" snapshots</b><i>"+(di===0?"↑":"↓")+"</i></button><div class='monitor-day-body "+(di===0?"open":"collapsed")+"'>"+hours+"</div></div>";
  }).join("");
  body.querySelectorAll(".monitor-day-toggle").forEach(b=>b.onclick=()=>{const d=b.nextElementSibling,o=d.classList.contains("collapsed");d.classList.toggle("collapsed",!o);d.classList.toggle("open",o);b.setAttribute("aria-expanded",String(o));b.querySelector("i").textContent=o?"↑":"↓"});
  body.querySelectorAll(".monitor-expand").forEach(b=>b.onclick=()=>{const d=b.closest(".monitor-row").querySelector(".monitor-result"),o=d.classList.contains("collapsed");d.classList.toggle("collapsed",!o);d.classList.toggle("open",o);b.textContent=o?"↑":"↓";b.setAttribute("aria-expanded",String(o))});
 };
 const renderDrops=()=>{const s=history.slice().sort((a,b)=>new Date(a.captured_at)-new Date(b.captured_at)),drops=[];for(let i=1;i<s.length;i++){const p=s[i-1],x=s[i],m=[["views",p.views,x.views],["likes",p.likes,x.likes],["comments",p.comments,x.comments],["shares",p.shares,x.shares],["saves",p.saves,x.saves]].filter(v=>v[1]!=null&&v[2]!=null&&Number(v[2])<Number(v[1]));if(m.length)drops.push({s:x,m})}const body=overlay.querySelector("#monitorBody");if(!drops.length){body.innerHTML="<div class='empty'>No drops detected yet.</div>";return}body.innerHTML=drops.reverse().map((d,i)=>"<div class='drop-row'><div class='drop-row-head'><div class='monitor-number'>"+(drops.length-i)+"</div><b>"+esc(fmt(d.s.captured_at))+"</b><span class='drop-badge'>DROP</span><button type='button' class='monitor-expand' aria-expanded='false'>↓</button></div><div class='drop-metrics collapsed'>"+d.m.map(x=>"<div><span>"+x[0].toUpperCase()+"</span><b class='down'>"+Number(x[1]).toLocaleString()+" → "+Number(x[2]).toLocaleString()+"</b></div>").join("")+"</div></div>").join("");body.querySelectorAll(".drop-row .monitor-expand").forEach(b=>b.onclick=()=>{const d=b.closest(".drop-row").querySelector(".drop-metrics"),o=d.classList.contains("collapsed");d.classList.toggle("collapsed",!o);b.textContent=o?"↑":"↓"})};
 try{const q=await api("history",{content_id:id}),rows=await q.json();if(!q.ok)throw new Error(rows.error||"Failed to load history");history=Array.isArray(rows)?rows:[];renderGrowth();}catch(e){overlay.querySelector("#monitorBody").innerHTML="<div class='empty'>Failed to load monitoring.<br><br>"+esc(e.message||e)+"</div>"}
 overlay.querySelectorAll(".monitor-tab").forEach(b=>b.onclick=()=>{overlay.querySelectorAll(".monitor-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");b.dataset.tab==="drops"?renderDrops():renderGrowth()});
};
})();